### index
GET http://localhost:8080/api/discounts
Accept: application/json
Authorization: Bearer my-secret-token

### show
GET http://localhost:8080/api/discounts/1
Accept: application/json
Authorization: Bearer my-secret-token

### Create
POST http://localhost:8080/api/discounts
Accept: application/json
Authorization: Bearer my-secret-token
Content-Type: application/json

{
    "tanggal": "2026-08-30",
    "nominal": 150000
}

### Update diubah sesuai 
PUT http://localhost:8080/api/discounts/1
Accept: application/json
Authorization: Bearer my-secret-token
Content-Type: application/json

{
    "tanggal": "2026-07-15",
    "nominal": 200000
}

### Delete 
DELETE http://localhost:8080/api/discounts/1
Accept: application/json
Authorization: Bearer my-secret-token