### Ambil semua data diskon (Read)
GET http://localhost:8080/api/discounts
Accept: application/json
Authorization: Bearer my-secret-token

### Ambil spesifik 1 data diskon (Misal ID 1)
GET http://localhost:8080/api/discounts/1
Accept: application/json
Authorization: Bearer my-secret-token

### Tambah data diskon baru (Create)
POST http://localhost:8080/api/discounts
Accept: application/json
Authorization: Bearer my-secret-token
Content-Type: application/json

{
    "kode_diskon": "PROMO2026",
    "potongan": 150000
}

### Ubah data diskon (Update - Misal ID 1)
PUT http://localhost:8080/api/discounts/1
Accept: application/json
Authorization: Bearer my-secret-token
Content-Type: application/json

{
    "kode_diskon": "PROMOUPDATE",
    "potongan": 200000
}

### Hapus data diskon (Delete - Misal ID 1)
DELETE http://localhost:8080/api/discounts/1
Accept: application/json
Authorization: Bearer my-secret-token